book_review_app/config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  resources :books
  resources :goodreads
  resources :i_dream_books

  get '/goodreads/:id' => 'goodreads#show'

  get '/i_dream_books/:id' => 'i_dream_books#show'

end

book_review_app/app/models/book.rb
class Book < ActiveRecord::Base
end

book_review_app/app/models/goodreads_api.rb
class Goodreads_Api < ActiveRecord::Base



  #Search goodreads through API

  def self.search_title(book)
    book = book
    key = ENV["GOODREADS_API_KEY"]
    request_string = 'https://www.goodreads.com/book/title.JSON?'
    escaped_request_string = URI.escape(request_string +'?key=' + key + '&title=' + book)
    response = HTTParty.get(escaped_request_string)

  end

  #Get results based on term search

 def self.search_author()

   key = ENV["GOODREADS_API_KEY"]
   request_string = 'https://www.goodreads.com/book/author/list.JSON?'
   escaped_request_string = URI.escape(request_string +'?key=' + key + '&author=' + book)
   response = HTTParty.get(escaped_request_string)

 end


 # Should I do it more like below so whatever I bring up works and just search by
 # term and id?  If so, will the below code work?

 # Get results based by term

 # def self.search_by_term(term)
 #   response = make_request("#{term}")
 #   return JSON.parse(response)['Search']
 # end

 #Returns results based on goodreads search

 # def self.search_by_id(id)
 #   response = make_request("#{id}")
 #   return JSON.parse(response)
 #
 #
 # end

end

book_review_app/app/models/i_dream_books_api.rb
class I_Dream_Books_Api < ActiveRecord::Base

  def search_i_dream_books()
    

    key = ENV["I_DREAM_BOOKS_API_KEY"]
    request_string = 'http://www.idreambooks.com/api/books/reviews.JSON?q='
    escaped_request_string = URI.escape(request_string + 'title=' + '?key=' + key + 'reviews')
    response = HTTParty.get(escaped_request_string)

  end
end

book_review_app/app/models/user.rb
class User < ActiveRecord::Base
end

book_review_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  # def search()
  #
  #   @goodreads = Goodreads_api.all
  #   @i_dream_books = I_dream_books_api.all
  #
  # end

end

book_review_app/app/controllers/goodreads_controller.rb
class GoodreadsController < ApplicationController

  def show()
    # Can I just search by title or author
  #  @goodreads = Goodreads.find(params[:title, :author, :review])

    
     render :json
  end

  private

  def goodreads_params

    params.require(:goodreads).permit(:title, :author, :small_image_url, :review)
  end

end

book_review_app/app/controllers/i_dream_books_controller.rb
class IDreamBooksController < ApplicationController

  def show

  end

end

book_review_app/app/views/goodreads/search.html.erb
<% form_tag application_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:title] %>
  <%= submit_tag "Search", :name => nil %>
</p>

<% end %>

<button>Search</button>

book_review_app/app/views/goodreads/show.html.erb
<h1>Goodreads</h1>
<%= form_tag("/goodreads/show", method: "get") do %>
<% @goodreads.each do |book| %>
<ul>
  <p><%= book.title %></p>
  <p><%= book.author %></p>
  <p><%= book.review %></p>
  <p><%= link_to "show", controllers_action_path %></p>
</ul>

<% end %>

book_review_app/app/views/i_dream_books/show.html.erb
<h1>I Dream Books</h1>

book_review_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReviewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div id = 'container'>
    <div id = 'header'>
      <h1>THE DAILY BOOK REVIEW</h1>
    </div>

    <div class = 'search'>
      <button>SEARCH</button>
    </div>

    <div class = 'goodreads'>
      <h2></h2>
    </div>

    <div class = 'i_dream_books'>
      <h2></h2>
    </div>
    <%= yield %>
  </div>



</body>
</html>